# Python review

Goals: 
- recall basic python vocab
- practice markdown

# libraries and packages

**librariy** a collecion of code that we can use to preform sepcific tasks in our programs

**NumPy**:
- core library for numerical computing in python
- many other libraries use numpy arrays as building blocks
- computions on numpy are optimined for speed and memory usage

lets impott numpy with **standard abrivation**

In [1]:
import numpy as np

## variables 

**variables** is a name we assign to a pirticular name in python

example: 

In [2]:
#here ima assign a small array to a variable a
a= np.array([[1,1,2],[3,5,8]])

In [4]:
# run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
#use `print()` to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## objects 

**object** (informally speaking is a bundle of properties and actions about something specific

ex:

object: data frame

properties: number rows, names of th ecollumns, date created

actions: selecting a specific row, adding a new collumn

a variable is the name we give a specific object, and the same object can be referenced by different variables.

in practive we often use variables and object interchanjebly 