# Python review

Goals: 
- recall basic python vocab
- practice markdown

# libraries and packages

**librariy** a collecion of code that we can use to preform sepcific tasks in our programs

**NumPy**:
- core library for numerical computing in python
- many other libraries use numpy arrays as building blocks
- computions on numpy are optimined for speed and memory usage

lets impott numpy with **standard abrivation**

In [1]:
import numpy as np

## variables 

**variables** is a name we assign to a pirticular name in python

example: 

In [2]:
#here ima assign a small array to a variable a
a= np.array([[1,1,2],[3,5,8]])

In [3]:
# run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
#use `print()` to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## objects 

**object** (informally speaking is a bundle of properties and actions about something specific

ex:

object: data frame

properties: number rows, names of th ecollumns, date created

actions: selecting a specific row, adding a new collumn

a variable is the name we give a specific object, and the same object can be referenced by different variables.

in practive we often use variables and object interchanjebly 

## Types

Every object in python has a type. the type tells us what kind of object it is.

we can also call the type of an object, the **class** of an object and they both mean what kind of object we have

In [5]:
print(a)

#check the type/class of variable with `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [7]:
print(a[0,0])

# Check the type on an entry on the array by indexing 
type(a[0,0])


1


numpy.int64

Notice that `type(a[0,0])` is a `numypy.int64` and not just the standard python integer type. This is telling us that 1 is an interger storeed as a 64-bit number.

In [10]:
a[1,1]

5

## FUnctions

`print` was our first example of a python **function**.

functions take in a set **aruments** and those argumants create an **output**.
argument = 

In [11]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has 2 types of arguments :
- non-optional arguments: argments you need to specify for the fucntion to do something
- optional arguments: arguments that are pre-filled with a default value by the fucntion. you can override thhem. optional arguments appear inside the parenthesis in the form optional_argiument=defualt_value

In [12]:
print("changing the default end argument", end=' :)')

changing the default end argument :)

## Atributes and methods

an object in python has atribures and methods

- atributres: a property of an object, some price of info about it
- method: a procedure assosiated with the object, an action where the main ingreiend is the object

### check in

fish attributes:

- length, color, species
- die(), bite(), swim()

**exmaple**
atributes for `numpy.arrays`

we can acseess vairbale attributes and methods by adding a period at th ened of the varables name

`variable.method()` or `variable.atribute`


In [13]:
a.shape

(2, 3)

In [14]:
type(a.shape)

tuple

In [15]:
# Methods examples
# min() returns the minimum value along a specified axis
a.min(axis=0)

array([1, 1, 2])

## check in

we can also call the `min` method without any parameters

In [16]:
a.min()

# Axis is an optional parameter

1

remeber : methods are function assosiated with an object. 

In [17]:
type(a.min)

builtin_function_or_method

## Exercie 

1. read the print function help. what is the typoe of the argument `sep`? is this an optional argument or non-optional argument? why?
2. create two new variables, onw with the integer value 77 and another onw with the string 99.
3. use your varuables to print `77%99%77` by changing the value of one of the optional arguments in `print`.

In [24]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [ ]:
#1 is an optional argument beause you cna stull run print without it. 
#2 

In [30]:
c = 77
d = '99'

In [33]:
print(c,d,c, sep='%')

77%99%77
